spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useUnicode=yes&serverTimezone=GMT%2B7
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/