spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useUnicode=yes&serverTimezone=GMT%2B7
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_updates: true
  #    properties:
#      hibernate:
#        format_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  servlet:
    context-path: /api

images:
  cabins:
    url: "http://localhost:8080/api/images/cabins/"
    path: "src/main/resources/static/images/cabins/"
  avatar:
    url: "http://localhost:8080/api/images/avatars/"
    path: "src/main/resources/static/images/avatars/"